services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/kam
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8080:8080"
    command: ["db:5432", "--", "java", "-jar", "app.jar"]
    networks:
      - my_network

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: kam
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: pass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
