name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          docker build -t my-kam-app .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Decode PEM file from secret
        run: echo "${{ secrets.AWS_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa

      - name: Set permissions on PEM file
        run: chmod 600 ~/.ssh/id_rsa

      - name: SSH to EC2 and deploy Docker container
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ~/.ssh/id_rsa
          script: |
            cd /home/ubuntu/app

            # Pull the latest changes from the main branch
            git pull origin main

            # Shut down the existing containers
            docker-compose down

            # Rebuild and restart the containers
            docker-compose up -d
